### ISSUE TITLE
WRF conversion error

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1729] opened 2019-06-21 20:59 UTC
Platform:
MacOS

To reproduce: 
1. Grab data files from `/glade/p/cisl/vast/vapor/data/Source/WRF/headwaters` and put them in `~/Temp/`
2. Create master.vdc file: `./wrfvdccreate ~/Temp/wrfout_d01_2053-03-2* ~/Temp/master.vdc`
3. Populate data file: `./wrf2vdc ~/Temp/wrfout_d01_2053-03-2* ~/Temp/master.vdc`
3. Wait for it to execute untill it reports the following error:
```
Copying variable U10
  Time step 0
  Time step 1
  Time step 2
  Time step 3
  Time step 4
  Time step 5
  Time step 6
  Time step 7
  Time step 8
  Time step 9
  Time step 10
  Time step 11
  Time step 12
  Time step 13
  Time step 14
  Time step 15
Copying variable UDROFF
  Time step 0
Error accessing netCDF file "/Users/shaomeng/Temp/master_data/data/UDROFF/UDROFF.0000.nc", nc_put_vara_double : NetCDF: Numeric conversion not representable -- file (/Users/stas/Documents/vapor/lib/wasp/NetCDFCpp.cpp), line(883)
Error accessing netCDF file "/Users/shaomeng/Temp/master_data/data/UDROFF/UDROFF.0000.nc", nc_put_vara_double : NetCDF: Numeric conversion not representable -- file (/Users/stas/Documents/vapor/lib/wasp/NetCDFCpp.cpp), line(883)
```

**Comment by sgpearse** [comment] 2019-06-27 19:22
Duplicate of #1623

**Closed by sgpearse** 2019-06-27 19:22 UTC
Labels: Bug, Rejected
