### ISSUE TITLE
Incorrect coordinate projections for some data sets

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#3052] opened 2022-02-23 21:54 UTC
The project from lat-lon to PCS coordinates is not performed correctly for some data, resulting in highly distorted visualizations. This is a regression that was introduced in VAPOR 3.6

To reproduce:
1. Load ROMS/Kauffman/*nc
2. Enable the image renderer

The results look like:

![ROMS_vapor3 6](https://user-images.githubusercontent.com/6777736/155415047-dcae892b-d4d6-47ec-899f-776d1bd44dfa.png)

The correct rendering generated by vapor 3.5 looks like:

![ROMS_vapor3 5](https://user-images.githubusercontent.com/6777736/155415098-8b509b60-3aaf-4a02-b2c9-4cbfeeeb82a4.png)

**Comment by clyne** [comment] 2022-02-23 23:03
Defer fixing until we have better automated integration testing

**Comment by shaomeng** [comment] 2022-09-21 06:36
On Casper, the follow error message occurs while importing data:

VAssert(rc >= 0) failed in LegacyVectorMath.cpp, line 901

**Comment by clyne** [comment] 2022-09-22 02:22
@shaomeng I can't reproduce this. Can you describe exactly what you are doing that generates an assert?

**Comment by shaomeng** [comment] 2022-09-22 05:33
> @shaomeng I can't reproduce this. Can you describe exactly what you are doing that generates an assert?

Must be a user mistake. I cannot reproduce it now. Closing again.

**Closed by shaomeng** 2022-09-22 05:33 UTC
Labels: Bug, High
