### ISSUE TITLE
Statistics: No. of Samples

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#413] opened 2017-11-16 22:53 UTC
I believe that the No. of Samples field may be off when using maximum refinement.  I may be wrong!

To reproduce:
1) Run Vapor with KatrinaMaster.nc
2) Open Statistics, add variable P, set the refinement level to 3 (315x309x34)
3) Make sure to maximize your extents in the GeometryWidget
4) The No. of Samples field reports 3,298,680.  Shouldn't it be 315x309x34=3,309,390?

The difference between the No. of Samples field and my calculation is 10,710, which is equal to our X dimension multiplied by our Z dimension.  Are we missing an XZ slice?

**Comment by shaomeng** [comment] 2017-11-18 22:02
I noticed the difference. 

Something else interesting is that with the 0th time step, the No. of Samples is reported 3,298,680, while with the 0th and 1st time steps, it is reported as 5819737. Two time steps doesn't yield twice samples. 

While looking at the code, it seems to me that the only chance the number of samples is off is from the missing value comparison (L790):
https://github.com/NCAR/VAPOR/blob/bf2d043fd8562097a75aed76e18de4f585f56940/apps/vaporgui/Statistics.cpp#L788-L801
@clyne do you think this is the cause?

**Comment by clyne** [comment] 2017-11-20 16:57
I believe the problem here is that some of the WRF data sets have moving domains: i.e. the geographic coordinates change over time. Presently, we have no way to select a moving region of interest. So when time steps are advanced the ROI does not change. I've opened a feature request to support this, 433, and labeled it Postponed.

**Comment by shaomeng** [comment] 2018-04-04 14:01
Update on 4/4/2018:
1. For the No. of Samples mismatch reported by Scott, the 0th step now reports the correct number of samples: 3,309,390 .
2. For the "two time slices doesn't have twice samples" reported by Sam, it's still the case. Given that issue #433 is still open, I defer to @clyne to decide if this issue needs to be kept open.

**Comment by clyne** [comment] 2018-04-06 20:53
I can't reproduce this so i'm closing it.

**Closed by clyne** 2018-04-06 20:53 UTC
Labels: Bug, High, works-for-me
