### ISSUE TITLE
Mapping range selector crashing as per Leigh's email

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1949] opened 2019-11-26 18:52 UTC
1. Import the NetCDF file at cisl-vapor/data/temp/issue1949
2. Create a 3D renderer
3. Set the variable to `qvpert`
3. Set the lower bounds to 0 using the mapping range selector text box

Vapor will crash

**Comment by shaomeng** [comment] 2019-11-26 22:15
Update: Sam tested on cisl-vapor and Casper without reproducing the crash.
This particular data is available on glade:
`/glade/work/shaomeng/VAPOR3.2-tmp/morgan1-top.03600.000000.nc`
and little_glade:
`/little_glade/data/LeighOrf_tricky/morgan1-top.03600.000000.nc`

**Comment by clyne** [comment] 2019-11-27 19:10
Given that this is happening inside of Qt (see Leigh's stack trace below) let's revisit - and have @leighorf retest - after Qt5 port is merged. 

Here's from gdb if that helps:

(gdb) where
#0  0x00007ffff12cf337 in raise () from /lib64/libc.so.6
#1  0x00007ffff12d0a28 in abort () from /lib64/libc.so.6
#2  0x00007ffff1311e87 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff131a679 in _int_free () from /lib64/libc.so.6
#4  0x00007ffff6412d40 in ?? () from /home/lorf/vapor-bleeding/lib/libQtCore.so.4
#5  0x00007ffff64109b9 in QMetaObject::changeGuard(QObject**, QObject*) () from /home/lorf/vapor-bleeding/lib/libQtCore.so.4
#6  0x00007ffff5b2ca31 in ?? () from /home/lorf/vapor-bleeding/lib/libQtGui.so.4
#7  0x00007ffff5b2d190 in QButtonGroup::removeButton(QAbstractButton*) () from /home/lorf/vapor-bleeding/lib/libQtGui.so.4
#8  0x00000000005a0879 in FidelityWidget::Update(VAPoR::DataMgr const*, VAPoR::ParamsMgr*, VAPoR::RenderParams*) ()
#9  0x000000000051ed9e in VariablesWidget::Update(VAPoR::DataMgr const*, VAPoR::ParamsMgr*, VAPoR::RenderParams*) ()
#10 0x00000000005b496a in VolumeEventRouter::_updateTab() ()
#11 0x0000000000480275 in EventRouter::updateTab() ()
#12 0x0000000000570108 in TabManager::_updateRouters() ()
#13 0x000000000054af0c in MainForm::eventFilter(QObject*, QEvent*) ()
#14 0x00007ffff63fa022 in QCoreApplicationPrivate::sendThroughApplicationEventFilters(QObject*, QEvent*) () from /home/lorf/vapor-bleeding/lib/libQtCore.so.4
#15 0x00007ffff5785be8 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/lorf/vapor-bleeding/lib/libQtGui.so.4
#16 0x00007ffff578c1da in QApplication::notify(QObject*, QEvent*) () from /home/lorf/vapor-bleeding/lib/libQtGui.so.4
#17 0x00007ffff63f9f4d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /home/lorf/vapor-bleeding/lib/libQtCore.so.4
#18 0x00007ffff63fcffd in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /home/lorf/vapor-bleeding/lib/libQtCore.so.4
#19 0x00007ffff6425f33 in ?? () from /home/lorf/vapor-bleeding/lib/libQtCore.so.4
#20 0x00007ffff078d099 in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
#21 0x00007ffff078d3f8 in g_main_context_iterate.isra.19 () from /lib64/libglib-2.0.so.0
#22 0x00007ffff078d4ac in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#23 0x00007ffff64257f5 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/lorf/vapor-bleeding/lib/libQtCore.so.4
#24 0x00007ffff5821716 in ?? () from /home/lorf/vapor-bleeding/lib/libQtGui.so.4
#25 0x00007ffff63f8b8f in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/lorf/vapor-bleeding/lib/libQtCore.so.4
#26 0x00007ffff63f8e85 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/lorf/vapor-bleeding/lib/libQtCore.so.4
#27 0x00007ffff63fde29 in QCoreApplication::exec() () from /home/lorf/vapor-bleeding/lib/libQtCore.so.4
#28 0x000000000047e01c in main ()
(gdb) 

On Tue, Nov 26, 2019 at 1:59 PM Leigh Orf <leigh.orf@ssec.wisc.edu> wrote:

I can reproduce the bug with the build you jsut sent me - lucky me!

I've attached the crash dump trace. Seems there is a different error.

Some info on my setup:

[lorf@orf ~]$ uname -a
Linux orf.ssec.wisc.edu 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[lorf@orf ~]$ cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)
[lorf@orf ~]$ nvidia-smi
Tue Nov 26 13:51:48 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.31       Driver Version: 440.31       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN RTX           Off  | 00000000:03:00.0  On |                  N/A |
| 40%   51C    P5    53W / 280W |   6269MiB / 24219MiB |     19%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2571      G   vapor                                       4213MiB |
|    0      5991      G   /usr/bin/X                                  1240MiB |
|    0      7304      G   cinnamon                                     453MiB |
|    0      9306      G   ...s=KAAAAAAAAAAgAAAgAAAAAAAAYAAAAAAAEAAAA   357MiB |
+-------------------------------------

**Comment by leighorf** [comment] 2019-11-27 19:14
FYI, I am at home today and I could not reproduce the bug on my CentOS
machine with ATI card. So the only machine it crashes on is the one I use
the most, hooray!

I can get around triggering the bug by using the slider first - then I can
enter whatever value I want.

Leigh

**Closed** 2019-12-12 16:03 UTC
Labels: Bug, Fixed, High
