### ISSUE TITLE
Vapor crashes when creating a Barb renderer on an MPAS data

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#41] opened 2017-10-16 05:47 UTC
To reproduce:
1) Open VAPOR, load an MPAS data. I tested /glade/p/VAST/VAPOR/Data/MPAS/MPAS_V4.0/x1.40962.output.2012-05-25_06.00.00.nc
2) create a Barb renderer.
3) click the checkbox to enable the renderer. Vapor crashes.

**Comment by sgpearse** [comment] 2017-10-24 17:46
John, I believe that the problem may lie within the DataMgr or Grid class for MPAS datasets.

The problem is deterministically reproducible.  On Geyser, the location of the crash is repeatable at MappingFrame.cpp:208, which is referencing an invalid Grid object.  The return code on DataMgrUtils::GetGrids is returning as valid, when the Grid object is NULL.

On OSX, the crash happens at seemingly random locations in the call trace.  For this reason I suggest debugging on Linux.

This problem does not seem to be exclusive to the Barb renderer.

**Comment by clyne** [comment] 2017-10-24 17:54
Just assign it to me, Scott, and i’ll take a look.

jc

> On Oct 24, 2017, at 11:46 AM, sgpearse <notifications@github.com> wrote:
> 
> John, I believe that the problem may lie within the DataMgr or Grid class for MPAS datasets.
> 
> The problem is deterministically reproducible. On Geyser, the location of the crash is repeatable at MappingFrame.cpp:208, which is referencing an invalid Grid object. The return code on DataMgrUtils::GetGrids is returning as valid, when the Grid object is NULL.
> 
> On OSX, the crash happens at seemingly random locations in the call trace. For this reason I suggest debugging on Linux.
> 
> This problem does not seem to be exclusive to the Barb renderer.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Closed** 2017-11-09 22:23 UTC
Labels: Bug, High, works-for-me
