### ISSUE TITLE
Crash on reading 3D variable from MPAS

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1731] opened 2019-06-21 21:55 UTC
OS Tested: OSX

1. Load the data set from glade MPAS/FalkoJudt/30km
1. Add a 3D renderer (Volume, Wireframe, Slice)
1. Select the variable `zxu`

Vapor will crash

**Comment by clyne** [comment] 2019-06-21 22:13
Stas, isn’t this a duplicate of #1637?

thanks - jc


> On Jun 21, 2019, at 3:55 PM, StasJ <notifications@github.com> wrote:
> 
> OS Tested: OSX
> 
> 	• Load the data set from glade MPAS/FalkoJudt/30km
> 	• Add a 3D renderer (Volume, Wireframe, Slice)
> 	• Select the variable zxu
> Vapor will crash
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by StasJ** [comment] 2019-06-21 22:16
@clyne 

That bug pertains to the DVR not supporting unstructured grids, yet it would try to load an unstructured grid.

This bug is unrelated to the DVR and occurs inside the vdc library.

**Closed** 2019-06-28 20:01 UTC
Labels: Bug, High
