### ISSUE TITLE
Vapor's Basic Renderer Controls documentation page is mostly out of date

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#3396] opened 2023-05-23 18:11 UTC
[https://ncar.github.io/VaporDocumentationWebsite/vaporApplicationReference/basicRendererControls.html](https://ncar.github.io/VaporDocumentationWebsite/vaporApplicationReference/basicRendererControls.html)

**Comment by sgpearse** [comment] 2024-09-25 16:56
Duplicate of #2624

**Closed by sgpearse** 2024-09-25 16:56 UTC
Labels: High, Documentation, ✓ still exists
