### ISSUE TITLE
CentOS installer fails to load data on Casper

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#3213] opened 2022-08-31 17:29 UTC
Using the CI build installer for CentOS (https://app.circleci.com/pipelines/github/NCAR/VAPOR/6044/workflows/b8483f9c-eee1-43e2-bba6-32acac75c105/jobs/14481/artifacts) to install VAPOR on Casper, the application launches OK. However, after attempting to load a data set (/glade/u/home/shaomeng/LeighOrf_24MayControl/24Maycontrol.04000.000000.nc), the application aborts with the following message:

```
qt.network.ssl: QSslSocket: cannot resolve OpenSSL_version_num
qt.network.ssl: QSslSocket: cannot resolve OpenSSL_version
qt.network.ssl: Incompatible version of OpenSSL
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00002b7966e2a040 (most recent call first):
Aborted
```

**Comment by sgpearse** [comment] 2022-08-31 17:49
Closing due to being a duplicate of #3190.

**Closed by sgpearse** 2022-08-31 17:49 UTC
Labels: Bug
