### ISSUE TITLE
Apply to all colorbars: not working

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#810] opened 2018-05-04 23:04 UTC
To reproduce: 
1. Open VAPOR, load Katrina.
2. Create a barb renderer. Enable it. Also Enable it's color bar. Leave the default settings.
2. Create a contour renderer. Enable it. Also Enable it's color bar. Change its default settings so the color bar look different from the barb renderer colorbar.
3. Click "Apply to all colorbars". Notice that the two colorbars are still looking different.

**Comment by clyne** [comment] 2018-05-05 15:29
This is a duplicate of 406

**Closed by clyne** 2018-05-05 15:29 UTC
Labels: Duplicate
