### ISSUE TITLE
Flow: selecting "no variable" results in no streamlines

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2085] opened 2020-01-12 19:38 UTC
If streamlines are generated using a 3D field changing the Z component
variable to "no variable" results in a blank screen. Re-setting the
Z component to an appropriate variable restores correct rendering.
However, at this point if the Variable Dimension is set to 2D again
nothing will be displayed.

To reproduce:
1. Load raw Katrina data, create a flow renderer, and enable it. The default field variables are U, V, and W. and everything is rendered correctly.

2. Change the Z component variable to "no variable". The display goes blank.

3. Change the Z component back to W. Rendering is correct again.
However, change the Variable Dimension to 2D and once again the
screen goes blank

Addendum:

Need to test with a single wrf file: wrfout_d02_2005-08-29_00

**Comment by shaomeng** [comment] 2020-01-14 21:23
Cannot reproduce on cisl-vapor. Need to be verified.

**Comment by clyne** [comment] 2020-01-14 22:17
@clyne please reverify

**Comment by clyne** [comment] 2020-01-14 23:12
@shaomeng I just that I can reproduce this as described above on my Mac. Could you test on the Mac. I've used both the release build as well as a debug build.

**Comment by shaomeng** [comment] 2020-01-14 23:18
Sounds good. I'll deal with other bugs first though, and not worry about
setting up development on my loaner laptop at this point.

**Comment by shaomeng** [comment] 2020-01-17 20:37
This bug isn't reproducible on MacOS too. Maybe the flow fixes in the past few days have also fixed this bug. I'll go ahead and close it.

**Comment by StasJ** [comment] 2020-01-21 19:05
I can reproduce this on my mac

**Comment by shaomeng** [comment] 2020-01-27 18:41
Hmm, cannot reproduce on either Mac or Linux.

**Comment by clyne** [comment] 2020-01-27 19:02
@stasj or @sgpearse if you are still able to reproduce this problem can you please sit with Sam and show him what you are doing? I'm not on the Mesa until this afternoon. Thanks

**Comment by sgpearse** [comment] 2020-01-27 19:19
I am able to reproduce this with the Katrina dataset produced with Vapor 3.0.

However if I use Katrina-3.2.0.alpha.nc, the problem does not persist.

**Comment by clyne** [comment] 2020-01-27 21:38
This problem still persists with the raw WRF files that are on glade.

**Comment by clyne** [comment] 2020-01-27 23:33
Not able to reproduce with current codebase.

**Comment by clyne** [comment] 2020-01-29 19:57
Can't verify until #2177 is fixed

**Closed** 2020-01-31 20:39 UTC
Labels: Bug, High
