### ISSUE TITLE
Region frame color has no effect

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1742] opened 2019-06-24 22:45 UTC
Recommended action: delete that option.

![Screenshot from 2019-06-24 16-43-30](https://user-images.githubusercontent.com/814885/60056814-87927680-969f-11e9-9040-50ec10c58a69.png)

**Comment by sgpearse** [comment] 2019-12-20 16:15
This is a duplicate of #1246

**Closed** 2024-04-04 15:55 UTC
Labels: Bug, Medium, No Longer Applicable
