### ISSUE TITLE
Hurricane Sandy conversion failed

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2007] opened 2019-12-17 17:30 UTC
The failure can be found in /little_glade/data/VDC/vapor-3.2.0.alpha/WRF/HurricaneSandy

**Comment by clyne** [comment] 2019-12-18 01:20
Duplicate of   #2018. Closing this ticket because #2018 has more information.

**Closed by clyne** 2019-12-18 01:20 UTC
Labels: Bug, Duplicate
