### ISSUE TITLE
Implicit time steps in NetCDF CF files not working

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR#1938] opened 2019-11-21 18:28 UTC
Attempts were made to make a static perspective relative to the storm and have the camera follow the hurricane, as opposed to having the model "run away" from a static camera. I tried changing the data individually and manually to make the screen distance and camera appearance the same, but this resulted in VAPOR behaving very strangely. The white box outline which shows the outer limits of the data moved independently from the camera, as opposed to staying where it was. So despite my efforts, the storm still managed to "move away" from the camera, despite the xyz coordinates and data being overwritten.

When I got to the seventh frame the model started to disappear. For some reason, despite displaying the white bounding box moving away, the "original" bounding box was still there, except it was invisible, and I could only tell that It existed based on the fact that it did not let anything at all be rendered outside of the original box. As a result, the model gets cut up and sliced until it passes the invisible bounding box entirely, at which point nothing becomes visible. This can be observed in the gif below, where the model becomes cut in half at the seventh frame, and then all subsequent frames get more and more cut off.
![stdo0](https://user-images.githubusercontent.com/56135291/69365636-a74cbb80-0c8c-11ea-96cf-11ea34c80f50.gif)

Finally, there are some stretchy rendering errors on the sides that didn't happen before with other rendering instances with the same data.

**Helpful additional information**
(*Please click check boxes AFTER submitting ticket*)
- [ ] Did VAPOR crash?
- [ ] Did you get wrong results?

**Impact**
- [ ] High - User productivity significantly degraded
- [ ] Medium - User productivity partially degraded
- [x] Low - User productivity trivially degraded

### To Reproduce
1. Import Netcdf file.
2. Enable renderers and adjust settings to view model.
3. Import new netcdf file with a different xyz coordinate.
4. Select "replace existing"
5. The white bounding box should have "jumped" away from its original location and rendered a model only in the overlapping areas of the original and new bounding box.

### Desktop
 - OS and version: [Redhat Enterprise Linux 7]
 - Version: [Vapor 3.2.0]

**Comment by StasJ** [comment] 2019-12-03 21:34
Hi, thank you for the detailed bug report. We currently support moving domain data however it is not intended to be with the "replace existing" feature. You can import multiple timesteps of your data by selecting multiple files at once in the import data menu. Then, you can access the timesteps with the menu in Vapor's top bar.

![s](https://user-images.githubusercontent.com/2772687/70091402-4355bb80-15d9-11ea-9ae8-f66ce01bc218.png)

This should fix some of the issues you were running into. We plan to add the ability for the camera to track a moving domain soon.

**Comment by jvalan** [comment] 2019-12-04 15:19
Thanks for your feedback, but that only reveals more problems. I attempted to create timesteps by importing data while selecting multiple files. However whenever I tried to view or render anything I recieved the error message "Paint Failed". This happened even when I tried using a mere two files as opposed to ten.

**Comment by StasJ** [comment] 2019-12-04 16:09
Sorry about that, I am not sure what it going wrong. If you are willing to share some of your data files with us, we can look into it further.

**Comment by jvalan** [comment] 2019-12-04 16:21
Here is a firefox one time download link with two of the files. I tried. https://send.firefox.com/download/0e5326a44c5c802c/#y95i2K3FU7TesyQGYXF1vw These are storm files, I found that it did not matter whether or not I was using core, storm or global files, as paint would fail all the same. Out of the three, I want storm files to work.

**Comment by jvalan** [comment] 2019-12-04 16:30
And then there's this file https://send.firefox.com/download/a384cab1d9dcab88/#xofi6jtxsCqXRQnHl0lC3w 

I am attempting to render something for pressure, which is a two dimension dataset, only when I try to render it with TwoDData or any of the other 2d renderers, I get a paint fail error as well.

**Comment by StasJ** [comment] 2019-12-04 17:14
I tested the two files you provided and I am running into the same problem. Individually, each time step works but if you try to import them together, vapor reports that there are no data variables and seems not to find the any extents. @clyne could you take a look at this? I've placed the datasets in `/little_glade/bugs/1938`

As to the third dataset you provided, it works but it appears to have a single 2D variable with a constant value.

**Comment by jvalan** [comment] 2019-12-04 17:36
Okay, for my last question, once these errors are fixed, do I have to wait for the next official release/official patch, or is there somewhere I can download an updated/bugfixed version?

**Comment by StasJ** [comment] 2019-12-04 19:56
The next official release is coming up soon however if we fix this issue I can build an installer for you

**Comment by jvalan** [comment] 2019-12-04 20:28
Thank you, I still am running on a version of 3.2.0 pre-release that was given to me early to improve the transfer function. There is also the matter of Flow renderers straight up crashing any time I try to create one. Vapor simply closes on itself, rather than give me an error message whenever I try to load of a big file into a dataset that doesn't default into one it can handle. The datasets that I have default to a value with ABSV which doesn't seem to be one that the 2d renderers can handle.

**Comment by clyne** [comment] 2019-12-06 17:21
> I tested the two files you provided and I am running into the same problem. Individually, each time step works but if you try to import them together, vapor reports that there are no data variables and seems not to find the any extents. @clyne could you take a look at this? I've placed the datasets in `/little_glade/bugs/1938`
> 
> As to the third dataset you provided, it works but it appears to have a single 2D variable with a constant value.

@stasj there are two different data sets mentioned above. Which ones are in /little_glade/bugs/1938? The data sets that are in /little_glade/bugs/1938 currently cannot be loaded as a time series because they don't contain a time dimension or time coordinate variable.  This is a bug, and we may be able to get it fixed for the release, but a quick workaround would be to include a time coordinate in the output files.

**Comment by jvalan** [comment] 2019-12-06 18:44
I do not know how to put time dimensions in or variables. I attempted to do that with ncat, ncecat, etc, but all were to no avail.

**Comment by StasJ** [comment] 2019-12-06 19:21
@clyne The datasets in /little_glade/bugs/1938 are the timesteps related to this bug. The other dataset is unrelated and was reported in #1961 so I put it in /little_glade/bugs/1961

**Comment by StasJ** [comment] 2019-12-06 19:23
@clyne if we cannot fix it before this release, we should add an error message informing users that a time dimension is missing.

**Comment by clyne** [comment] 2019-12-06 19:48
Agreed. 

> On Dec 6, 2019, at 12:23 PM, StasJ <notifications@github.com> wrote:
> 
> @clyne if we cannot fix it before this release, we should add an error message informing users that a time dimension is missing.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by StasJ** [comment] 2019-12-16 18:11
@clyne It seems that this issue was reintroduced and vapor will once again crash if you try to import those two files at the same time.

**Comment by clyne** [comment] 2019-12-19 22:22
@stasj I can't reproduce this. What platform are you running on?

**Comment by clyne** [comment] 2019-12-19 23:20
OK. I’m closing it again and we’ll pick it up again in the next round.

> On Dec 19, 2019, at 3:47 PM, StasJ <notifications@github.com> wrote:
> 
> @clyne I cannot reproduce this either. @sgpearse reopened this.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Closed** 2019-12-20 18:18 UTC
Labels: Bug, Fixed, High
