### ISSUE TITLE
Volume Renderer is not consistent as refinement level increases

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1090] opened 2018-12-13 23:29 UTC
Dataset: Katrina
Variable: U

![out](https://user-images.githubusercontent.com/2772687/49973913-39343c00-fef4-11e8-8e02-b7ef20e35e8a.gif)

**Comment by shaomeng** [comment] 2018-12-14 21:58
I wasn't able to reproduce this bug on development branch `issue1073`. Will try again once this branch is merged.

**Comment by shaomeng** [comment] 2018-12-14 23:30
After PR  #1091 got merged, I still cannot reproduce this bug. Need more detail.

**Closed** 2018-12-19 22:38 UTC
Labels: Bug, Works For Me
