### ISSUE TITLE
Corrupt image renderer

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1353] opened 2019-01-23 17:59 UTC
1. Import `WRF/rotlatlon/Alan2/d01`
2. Create/enable an image renderer

<img width="645" alt="screen shot 2019-01-23 at 10 57 55 am" src="https://user-images.githubusercontent.com/2772687/51626886-ce681e80-1efd-11e9-9776-fb0fae54547a.png">

**Comment by clyne** [comment] 2022-08-29 14:11
Duplicate of #3201

**Closed by clyne** 2022-08-29 14:11 UTC
Labels: Duplicate, Bug, Low
