### ISSUE TITLE
two variable colored dvr exhibits visualization artifacts.

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1922] opened 2019-11-15 22:18 UTC
### Describe the bug
Using two variable colored dvr, there's obvious artifacts. See the screenshot and the session file. 
(You will need to open the attached PNG in full resolution to see them. They appear on the upper side of the rendering. )

Test system is cisl-vapor. 

![dvr-color](https://user-images.githubusercontent.com/814885/68979512-ff7e4c00-07ba-11ea-8a7d-ea29034da3c1.png)

[dvr-color.vs3.zip](https://github.com/NCAR/VAPOR/files/3853376/dvr-color.vs3.zip)

**Comment by StasJ** [comment] 2019-11-15 22:35
This is a duplicate of #1851, #1737, and #1681

**Closed** 2019-11-20 21:40 UTC
Labels: Bug, Duplicate
