### ISSUE TITLE
Changing flow color mapped var causes paths to break

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2936] opened 2021-12-16 16:32 UTC
1. Open `/glade/p/cisl/vast/vapor/Bugs/2936/2936.vs3`
2. Change the Color Mapped Variable

Notice that the flow paths have changed and are now incorrect.

<img width="438" alt="ss" src="https://user-images.githubusercontent.com/2772687/146833384-a47adea7-74cd-4154-ada0-de310531296b.png">

**Comment by shaomeng** [comment] 2021-12-21 05:27
With the presence of bug #2941 it's hard to debug this one, so will wait till #2941 is fixed.

**Comment by clyne** [comment] 2022-01-18 21:55
Could possibly debug on casper. Problematic because of working from china.

**Comment by shaomeng** [comment] 2022-02-01 09:19
This reported bug seems to be triggered by a user action that has undefined consequences: 
The session file specifies "integrate particle values along trajectory" while the reproduction steps specifies "Change the Color Mapped Variable."

**Comment by StasJ** [comment] 2022-02-01 18:26
> This reported bug seems to be triggered by a user action that has undefined consequences: The session file specifies "integrate particle values along trajectory" while the reproduction steps specifies "Change the Color Mapped Variable."
> 
> In normal use cases, e.g., changing color mapping variables while trajectories are supposed to be colored by a variable, this bug is not observed.

The particle integration mode only effects the particle values and thus is unrelated to this bug in which the particle positions are wrong. You can confirm by changing the integration mode of the session file and re-testing.

**Comment by shaomeng** [comment] 2022-02-02 10:19
Hi @StasJ I have found the cause of this issue, and I'm afraid I'll have to kick it back to you to fix some integration handles. Here is an explanation and please let me know if you feel confused. 

1. There are two types of particles stored in a "stream": regular particles and *special* particles. Whether it's a special particle can be tested by querying the Particle.IsSpecial() method. The technical difference between a regular and special particle is that a special particle has its "time" and "value" field both set to "NAN."
2. While regular particles hold legit information and should be rendered, special ones only indicate the break of a trajectory, and should not be rendered. Actually, your advanced rendering algorithm handles this correctly.
3. Special particles are inserted by the advection code and should not be changed to non-special particles when you change colors of particles. I.e., the color changing algorithm should only apply new colors to regular particles.
4. Somewhere in the advanced integration coloring code, non-NAN floating point values are assigned to the "value" field of special particles. As a result, they lost their special properties, and the rendering code paints them on the screen. 

So the proper fix is to test special particles and skip ones test true when you do advanced coloring, thus they remain special. Does this make sense?

**Comment by StasJ** [comment] 2022-02-02 18:21
Sam, the advanced coloring code handles your "special" particle scheme correctly and is not at fault here. This can be attested by the fact that the bug occurs with the advanced coloring mode disabled.

**Comment by shaomeng** [comment] 2022-02-03 01:56
@StasJ I was not able to trigger this bug without involving in advanced coloring. If you have a reproducible sequence, I'm happy to know. 

However, I was able to locate one particle that is changed to non-special status from special status by the "advanced coloring" code with the following steps:
1. Load the attached session file, and change the dataset to the same one in this original bug report uses.
2. Add a few lines of code to print out the value of the last particle in stream number 4, no matter it's special or not.
3. Enable the Flow renderer. The print message shows that the particle in question is "special."
4. Navigate to the "Integration" tab, and click the checkbox "Integrate particles along trajectory". The print message shows that the particle in question is no longer "special."

Note, in step 4, that checkbox operation should not change a special particle to non-special. Does this make sense?

**Comment by StasJ** [comment] 2022-02-03 19:54
> @StasJ I was not able to trigger this bug without involving in advanced coloring. If you have a reproducible sequence, I'm happy to know.

If you disable advanced coloring in the linked session file, the same issue occurs.

**Comment by clyne** [comment] 2022-02-03 20:51
Does it occur in 3.5, prior to the introduction of "advanced coloring"?

**Comment by StasJ** [comment] 2022-02-03 21:51
> Does it occur in 3.5, prior to the introduction of "advanced coloring"?

Yes.

**Comment by shaomeng** [comment] 2022-02-04 00:48
> > @StasJ I was not able to trigger this bug without involving in advanced coloring. If you have a reproducible sequence, I'm happy to know.
> 
> If you disable advanced coloring in the linked session file, the same issue occurs.

My test shows that the step of "disabling advanced coloring" changes a handful of special particles to non-special particles, thus breaking the functionality. Unfortunately, I don't know how "disabling advanced coloring" works so I cannot fix it. 

The test that demonstrates this behavior of "disabling advanced coloring" is documented with reproducible steps in my last comment.

Also, because it's the step of "disabling advanced coloring" that breaks the functionality, I cannot reproduce the bug in 3.5. If @StasJ has a sequence to do so, please share it.

**Comment by StasJ** [comment] 2022-02-04 08:57
> Also, because it's the step of "disabling advanced coloring" that breaks the functionality, I cannot reproduce the bug in 3.5. If @StasJ has a sequence to do so, please share it.

The step of "disabling advanced coloring" has nothing to do with the bug. It is just to show you that the bug occurs without it. Since "advanced coloring" does not exist in 3.5, it is irrelevant. Did you try to reproduce the bug in 3.5?

**Comment by shaomeng** [comment] 2022-02-04 11:42
Hi Stas, I've tested in 3.5 but I cannot reproduce it. If you have discovered a sequence of steps to trigger it, I'm happy to learn.

**Comment by clyne** [comment] 2022-02-04 15:24
@StasJ, @shaomeng I might suggest that you two set up a time to screen share so that we can move this forward. thanks

**Comment by shaomeng** [comment] 2022-02-07 13:44
No need to zoom; I've figured out the problem. Thanks to @clyne and @StasJ for your input.

**Closed** 2022-02-07 21:40 UTC
Labels: Bug, High
