### ISSUE TITLE
Error is occuring while creating Wind variable

### ISSUE THREAD

**Issue by onurhdogan** [NCAR/VAPOR#2056] opened 2020-01-05 12:09 UTC
### Describe the bug
Hello
I would like to create wind variable with a wrfout.nc data. I have U,V and W variables. 
While I try "wind=(U*U+V*V+W*W)**0.5" command on python it is giving error at below.
I understand that U and V variable shapes are not comply with each other (363 and 364) but I could not any suggest about it. I have just a wrf nc data, so creating vdc is unnecessary. 
On this situation, I could not create upper level streamline. Thank you
""""""""""""""""""""
Failed to read variable "wind" at time step (0), and
refinement level (-1) and level-of-detail (-1)
Failed to read region from variable/timestep/level/lod (wind, 0, -1, -1)
PyRun_String() : Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: operands could not be broadcast together with shapes (39,363,547) (39,364,546)
""""""""""""""""""""""

**Comment by clyne** [comment] 2020-01-06 16:34
The U, V, and W components of velocity are computed on a staggered Arakawa C-grid. The easiest way to compute the magnitude of the field is to use the vapor_utils.Mag() function, which resamples all of the components to the base (unstaggered grid). Your script would look like:

import vapor_utils as vu
wind = vu.Mag(U,V,W)

IMPORTANT NOTE: you need to select an appropriate output mesh (grid) when you define the output variable in the script editor. The mesh should be set to "west_eastXsouth_northXbottom_top".

**Comment by onurhdogan** [comment] 2020-01-06 19:04
Thank you very much for your interest but it gives new error at below. I have chose as west_eastXsouth_northXbottom_top

""""""""""
Failed to read variable "ohd" at time step (0), and
refinement level (-1) and level-of-detail (-1)
Failed to read region from variable/timestep/level/lod (ohd, 0, -1, -1)
PyRun_String() : Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/onurhdogan/Downloads/Vapor/share/python/vapor_utils.py", line 143, in Mag
    tmp = StaggeredToUnstaggeredGrid(argv[i], axis)
  File "/home/onurhdogan/Downloads/Vapor/share/python/vapor_utils.py", line 78, in StaggeredToUnstaggeredGrid
    aprime[k,::,::] =  _StaggeredToUnstaggeredGrid2D(a[k,::,::],axis-1)
  File "/home/onurhdogan/Downloads/Vapor/share/python/vapor_utils.py", line 20, in _StaggeredToUnstaggeredGrid2D
    from scipy.interpolate import RectBivariateSpline
ImportError: No module named scipy.interpolate
"""""

**Comment by clyne** [comment] 2020-01-06 20:24
What operating system are you using? The 3.1 installer for Linux was missing the SciPy library. 

> On Jan 6, 2020, at 12:04 PM, OnurHDogan <notifications@github.com> wrote:
> 
> Thank you very much for your interest but it gives new error at below. I have chose as west_eastXsouth_northXbottom_top
> 
> """"""""""
> Failed to read variable "ohd" at time step (0), and
> refinement level (-1) and level-of-detail (-1)
> Failed to read region from variable/timestep/level/lod (ohd, 0, -1, -1)
> PyRun_String() : Traceback (most recent call last):
> File "", line 2, in 
> File "/home/onurhdogan/Downloads/Vapor/share/python/vapor_utils.py", line 143, in Mag
> tmp = StaggeredToUnstaggeredGrid(argv[i], axis)
> File "/home/onurhdogan/Downloads/Vapor/share/python/vapor_utils.py", line 78, in StaggeredToUnstaggeredGrid
> aprime[k,::,::] = _StaggeredToUnstaggeredGrid2D(a[k,::,::],axis-1)
> File "/home/onurhdogan/Downloads/Vapor/share/python/vapor_utils.py", line 20, in _StaggeredToUnstaggeredGrid2D
> from scipy.interpolate import RectBivariateSpline
> ImportError: No module named scipy.interpolate
> """""
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by onurhdogan** [comment] 2020-01-07 07:47
I am using Ubuntu 18. 
It has done when I am using my Windows 8 but, as you said linux has given that error. 
Is there any possibility showing SciPy packace in Linux system? 
Thank you very much for your reply

**Comment by clyne** [comment] 2020-01-07 18:59
This problem has been fixed in VAPOR 3.2, which we expect to release by the end of the month. We would have a pre-release for Ubuntu by the end this week. If you’d like to test the pre-release we can arrange that. Just let us know.


> On Jan 7, 2020, at 12:47 AM, OnurHDogan <notifications@github.com> wrote:
> 
> I am using Ubuntu 18.
> It has done when I am using my Windows 8 but, as you said linux has given that error.
> Is there any possibility showing SciPy packace in Linux system?
> Thank you very much for your reply
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by onurhdogan** [comment] 2020-01-08 09:14
I would like to test pre-release for ubuntu, thank you very much

**Comment by clyne** [comment] 2020-01-08 22:49
We’ll let you know as soon as we have one ready.

> On Jan 8, 2020, at 2:14 AM, OnurHDogan <notifications@github.com> wrote:
> 
> I would like to test pre-release for ubuntu, thank you very much
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by shaomeng** [comment] 2020-01-10 02:41
Hello @onurhdogan , we have built a new installer which we hope have resolved this SciPy issue. Do you mind giving it a try? 
https://drive.google.com/a/ucar.edu/file/d/1JKtHSMc-nn6a0S453R89UTu2G37O_dMn/view?usp=sharing

**Comment by onurhdogan** [comment] 2020-01-12 09:37
@shaomeng hello. 
SciPy package has runned successfully but when I push new button for new renderer type after python running, it is stopping on black screen (I tried 3 times). 
I put the attach that screen in attachment, before python variable it is working without error. Thank you
![vapor3](https://user-images.githubusercontent.com/45236135/72216884-006ff780-3538-11ea-8cc4-3e4c1b9de524.png)

**Comment by clyne** [comment] 2020-01-16 13:56
@onurhdogan can you please describe exactly the steps you are going through to reproduce this problem?

**Comment by sgpearse** [comment] 2020-06-24 14:11
Cannot reproduce with current installer.

**Closed by sgpearse** 2020-06-24 14:11 UTC
Labels: Bug, High
