### ISSUE TITLE
M1 mac installer "damaged"

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#3436] opened 2023-08-18 15:08 UTC
<img width="252" alt="s" src="https://github.com/NCAR/VAPOR/assets/2772687/e89d2bc4-4c05-49ad-8afe-e10d922658fd">

**Comment by sgpearse** [comment] 2023-08-18 15:19
Related to #2375.  We need to get Vapor registered with Apple.

To get around this the user will need to remove the quarantine flag:
`sudo xattr -rds com.apple.quarantine /Applications/vapor.app`

**Comment by NihanthCW** [comment] 2023-08-18 16:09
@sgpearse I think we've discussed this before - I want us to be quite certain that this is the cause since the error dialogue is different in #2375 ? 
I agree that verifying the app is something that we need to do, I want us to diagnose the issue carefully and rule out any other potential issues before going down that road.

**Comment by NihanthCW** [comment] 2023-08-21 18:11
Meeting update:
Let's move forward with modifying the extended attributes (xattr) and run tests thoroughly. We can determine the course of action based on the test results. 
If all looks okay after testing, then we can proceed with this option until we register the app with apple and test the developer hypothesis.

**Comment by StasJ** [comment] 2024-04-23 00:55
Still warns of unknown developer and takes two attempts to open due to this, but the installer is no longer "damaged"

**Comment by shaomeng** [comment] 2024-08-07 23:24
Still shows "unverified developer" on M1, and I won't be able to use VAPOR.

<img width="276" alt="Screenshot 2024-08-07 at 4 23 13 PM" src="https://github.com/user-attachments/assets/9b97e2c4-5a6e-479b-a5fd-db6478dc6820">

**Comment by sgpearse** [comment] 2024-08-07 23:52
@shaomeng Could you also tag which operating system version you're running on appleSilicon?

**Comment by shaomeng** [comment] 2024-08-08 18:19
It works well after I downloaded the correct installer. There's no problem here. Closing it now.

**Closed by shaomeng** 2024-08-08 18:19 UTC
Labels: Bug, High, Fixed, testing
