### ISSUE TITLE
Barb: undo breaks color bar.

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1389] opened 2019-01-25 23:48 UTC
Starting from the state reported in issue #1388 (session file and screenshot), if an `undo` is issued, the color bar will break, becoming super wide:

![screenshot from 2019-01-25 16-46-01](https://user-images.githubusercontent.com/814885/51778808-f5bb1900-20c0-11e9-8ab1-6f62f7ed1e6d.png)

**Comment by shaomeng** [comment] 2019-01-26 00:07
Update: This behavior seems to present in all renderers, and it happens as soon as colorbar is enabled.

**Comment by sgpearse** [comment] 2019-01-28 14:49
Thanks for reporting.  This one is actually a duplicate of #1308, which was classified as medium priority.

**Closed** 2019-01-28 19:03 UTC
Labels: Bug, Duplicate, Rejected
