### ISSUE TITLE
2D Wireframe regression

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1403] opened 2019-01-26 22:50 UTC
The wireframe renderer once again no longer works with 2D variables.

1. Open Katrina
2. Add/enable a 2D wireframe renderer

You will not see anything rendered. If you rotate the scene, you may see glimpses of the wireframe.

This is caused by the wrong orientation being set. Despite this being a 2D variable, the orientation `XYZ` is set.

**Comment by sgpearse** [comment] 2019-01-28 21:15
Duplicate of #1395

**Closed by sgpearse** 2019-01-28 21:15 UTC
Labels: Bug, Fixed, High
