### ISSUE TITLE
ROMS-Kauffman grid appears to be incorrectly stretched

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#3203] opened 2022-08-29 06:04 UTC
![ROMS-Kauffman-TwoDData](https://user-images.githubusercontent.com/2772687/187133400-c1736a8c-ee71-4c26-858d-bfbe990c2679.png)
[ROMS-Kauffman-TwoDData.png.log](https://github.com/NCAR/VAPOR/files/9441909/ROMS-Kauffman-TwoDData.png.log)
[ROMS-Kauffman-TwoDData.png.vs3.zip](https://github.com/NCAR/VAPOR/files/9441910/ROMS-Kauffman-TwoDData.png.vs3.zip)
![ROMS-Kauffman-Volume](https://user-images.githubusercontent.com/2772687/187133401-30b11db3-a926-4eeb-8152-1f2da1b76320.png)
[ROMS-Kauffman-Volume.png.log](https://github.com/NCAR/VAPOR/files/9441911/ROMS-Kauffman-Volume.png.log)
[ROMS-Kauffman-Volume.png.vs3.zip](https://github.com/NCAR/VAPOR/files/9441912/ROMS-Kauffman-Volume.png.vs3.zip)

**Comment by clyne** [comment] 2022-09-06 22:14
@StasJ re-assigning this to you. If these data are loaded from the GUI and displayed with the default session everything looks correct. If I used the attached session file I get the same results are reported above.  In the session file you have attached the map projection string is set to:

`+proj=eqc +ellps=WGS84 +lon_0=20.1187 +lat_0=46.1279`

However, the default projection string computed by the GUI is 

`+proj=eqc +ellps=WGS84 +lon_0=196.769\+lat_0=46.1279`

If the projection string is changed to the default calculated by the GUI everything looks ok. Not sure where the projection string in the offending session file is coming from.

**Comment by StasJ** [comment] 2022-09-08 04:47
So far I can't figure that out either but I don't think its related to the python API. I tried multiple build configurations on my mac and I cannot reproduce the issue in either the GUI or the Python API. When I run the mac weekly installer, however, the issue presents itself in the GUI. On CentOS if I build an installer, the GUI works, but the python api built with Conda does not.

**Comment by clyne** [comment] 2022-09-08 18:03
I can't reproduce the problem with the Version: 3.6.1.b24d5b828 installer on my Mac. I wonder if this is related to #3220. There seems to an inconsistency in which libgeotiff libraries are being used. Perhaps we table this until @sgpearse sorts the issue out and we have the right libgeotiff library (1.7.1) installed everywhere.

**Comment by StasJ** [comment] 2022-09-10 04:40
So it turns out this was just a bug that was coincidentally fixed in the last week which explains why it was so difficult to reproduce :shrug:.

**Closed** 2022-09-11 00:16 UTC
Labels: Bug, High
