### ISSUE TITLE
WRF-HRRR Volume and IsoSurface render nothing

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#3202] opened 2022-08-29 06:02 UTC
![WRF-HRRR-IsoSurface](https://user-images.githubusercontent.com/2772687/187133245-b5b7ef42-e1f1-4592-b839-14a7045ce50f.png)
[WRF-HRRR-IsoSurface.png.log](https://github.com/NCAR/VAPOR/files/9441904/WRF-HRRR-IsoSurface.png.log)
[WRF-HRRR-IsoSurface.png.vs3.zip](https://github.com/NCAR/VAPOR/files/9441905/WRF-HRRR-IsoSurface.png.vs3.zip)
![WRF-HRRR-Volume](https://user-images.githubusercontent.com/2772687/187133248-3682b757-076b-4654-9aa0-4c32ce643e05.png)
[WRF-HRRR-Volume.png.log](https://github.com/NCAR/VAPOR/files/9441906/WRF-HRRR-Volume.png.log)
[WRF-HRRR-Volume.png.vs3.zip](https://github.com/NCAR/VAPOR/files/9441907/WRF-HRRR-Volume.png.vs3.zip)

**Comment by clyne** [comment] 2022-09-06 22:35
Works for me on my Mac:

Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,2
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	512 KB
  L3 Cache:	8 MB
  Hyper-Threading Technology:	Enabled
  Memory:	32 GB
  System Firmware Version:	1554.140.20.0.0 (iBridge: 18.16.14759.0.1,0)

**Comment by shaomeng** [comment] 2022-09-22 05:44
Using 9/20/2022 installer, the following message shows up when enabling a volume renderer:

Error performing paint event
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Error retrieving variable data
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Failed to read region from variable/timestep/level/lod (Elevation, 0, -1, -1)
nc_get_vara_float(65536, 168) : NetCDF: Start+count exceeds dimension bound
Redirecting Python IO
------------------
Vapor 3.6.1.6d15602
OS: Linux 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020
Distro:
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch

**Comment by sgpearse** [comment] 2022-09-22 18:17
We will visit this on Tuesday.

**Comment by sgpearse** [comment] 2022-09-22 18:34
Fix #3177

**Comment by clyne** [comment] 2022-09-22 19:32
@shaomeng what Linux platform are you running on? This works fine for me on Casper and my Mac.

**Comment by shaomeng** [comment] 2022-09-23 18:08
> @shaomeng what Linux platform are you running on? This works fine for me on Casper and my Mac.

It was Casper. I also added a few steps to reproduce the error message.

**Comment by clyne** [comment] 2022-09-23 23:18
I still can't reproduce this even on Casper. I get an error that the volume rendering can't render a volume with a dimension of 1, which is reasonable. Note that the two data sets in this directory should probably not be combined. They both define the same variable names, but with different dimensions. We should probably put them in different directories or something.

**Comment by shaomeng** [comment] 2022-09-24 03:28
Hmm, I seem to no longer be able to reproduce it as well. It might be user mistake earlier, sorry. I'll close this one for now.

**Closed by shaomeng** 2022-09-24 03:28 UTC
Labels: Bug, High
