### ISSUE TITLE
TFE: Loading a color map snaps the data range extents back to original values

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#629] opened 2018-04-16 14:34 UTC
If a color map is loaded from a file the TFE range extents are set back to
their original values.

To reproduce:

1. Load Katrina and enable the 2D data renderer with the PSFC variable
2. Change the TFE min or max extent to something other than the default value.
3. Load a color map from a file. The range extents change back to their
original values.

**Comment by shaomeng** [comment] 2018-04-16 15:35
Is this a duplicate of #603 ?

**Comment by StasJ** [comment] 2018-04-17 18:07
Needs discussion

**Comment by clyne** [comment] 2018-04-21 19:09
This is not a bug. It's just a different use case. There are times when you want to load a map and have it use whatever range the map was saved with, and times when you want the loaded map to use the currently defined range in the GUI. I've changed this to a feature request.

**Closed** 2020-03-20 04:12 UTC
Labels: Enhancement, Fixed, High
