### ISSUE TITLE
Barb: Default data fidelity not working

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#251] opened 2017-11-07 22:50 UTC
To reproduce:

1. load Katrina, create a barb renderer
2. Change the Fidelity value to any available ones.
3. Click "Default" button. Nothing happens.

**Comment by sgpearse** [comment] 2017-11-08 21:39
Marking as duplicate of bug [243](https://github.com/NCAR/VAPOR/issues/243)

**Closed** 2017-11-08 22:09 UTC
Labels: Bug, Duplicate, High
