### ISSUE TITLE
BarbParams::_init does not set default variable or gracefully fail when none found

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#172] opened 2017-10-27 21:56 UTC
If `_dataMgr->GetDataVarNames` returns an empty array, `SetVariableName` is called with the string "". This causes problems later.

**Comment by sgpearse** [comment] 2017-11-06 16:48
Unable to reproduce.  Need a procedure.  Maybe it got fixed in the last pull request?

**Closed** 2017-11-06 18:04 UTC
Labels: Bug, works-for-me
