### ISSUE TITLE
Refactor: clang tidy

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2251] opened 2020-03-20 19:02 UTC
### Description
Refactor the existing code base to comply some c++ code standards. One good candidate is c++ core profile.

### Step 1: assessment
Assess the current state of VAPOR code base to see how much it is adhering to a profile, and how much effort is required to refactor it to comply.

### Step 2: decision making
Based on the outcome of Step 1, decide if we want to go fully comply with a c++ code standard.

**Comment by sgpearse** [comment] 2022-04-13 15:26
Duplicate of #2759.

**Closed by sgpearse** 2022-04-13 15:26 UTC
Labels: Developer Feature
