### ISSUE TITLE
Vertical slice geometry not loading from session file

### ISSUE THREAD

**Issue by phawbeck** [NCAR/VAPOR#2698] opened 2021-04-08 14:40 UTC
When a vertical slice (XZ or YZ) is created and saved in a session file, it is reverted to an XY slice when opening the session file.

**Helpful additional information**
(*Please click check boxes AFTER submitting ticket*)
- [ ] Did VAPOR crash?
- [x] Did you get wrong results?

**Impact**
- [ ] High - User productivity significantly degraded
- [x] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### To Reproduce
Steps to reproduce the behavior. For example:
1. Create a XZ or YZ slice of some variable
2. Modify geometry (location, min/max)
3. Save session
4. Load session

*Additionally, please attach a session file to this ticket to easily reproduce (use File->Save Session).*
[slice_test.vs3.txt](https://github.com/NCAR/VAPOR/files/6279440/slice_test.vs3.txt)

### Expected behavior
Load in the slices as they were saved.

### Attachments
<img width="1192" alt="SliceLoaded" src="https://user-images.githubusercontent.com/39134281/114046266-efe72380-9845-11eb-8de5-750b89fe7aaf.png">
<img width="1254" alt="SliceSaved" src="https://user-images.githubusercontent.com/39134281/114046282-f37aaa80-9845-11eb-8517-5dbfe99dcda8.png">

### Desktop
 - OS and version: Centos 7 (Casper VNC)
 - Version: Vapor 3.2

**Comment by StasJ** [comment] 2021-04-12 19:06
Hi Pat,

I noticed you are using vapor 3.2. I could not reproduce this bug in vapor 3.4 so if you download the latest version it should work correctly.

Thanks,
Stas

**Comment by clyne** [comment] 2021-04-13 20:57
Fixed in 3.4

**Closed by clyne** 2021-04-13 20:57 UTC
Labels: Bug
