### ISSUE TITLE
3D variables with a dimension of length one are not handled correctly

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1375] opened 2019-01-25 05:17 UTC
In `Katrina`, the 3D variable `TSLB` causes some weird behavior:
- In the Slice renderer, it renderers but only for the first few refinement levels
- The wireframe renderer shows nothing
- The volume renderer freaks out:

![out](https://user-images.githubusercontent.com/2772687/51726663-b095d900-2025-11e9-9957-03b8ff2b3b9a.gif)

**Comment by clyne** [comment] 2019-12-20 20:35
Works for me. @stasj can you be more specific about what you are doing? FYI the default Z coordinate is top of the domain, which results in nothing being shown as might be expected. You'll need to move it.

**Comment by StasJ** [comment] 2019-12-20 21:14
1. Open Katrina from `/little_glade/data/VDC/vapor-3.2.0.alpha/WRF/Katrina`
2. Create a wireframe renderer
3. Select the variable `TSLB`
4. Enable the renderer

Nothing will be shown. I just checked and I can reproduce it following the above steps. I'm not sure what you mean by the Z coordinate being at the top of the domain. The geometry widget shows that the Z min and Z max of this variable are both 2.

<img width="872" alt="Screen Shot 2019-12-20 at 2 08 24 PM" src="https://user-images.githubusercontent.com/2772687/71293538-f3922680-2332-11ea-94b3-c1b85d1af2c2.png">

**Comment by clyne** [comment] 2020-01-02 19:07
Stalled pending resolution of #2048

**Comment by clyne** [comment] 2020-01-03 22:57
I am handing this over @sgpearse . Scott, note that there is an open branch with a partial fix, named "issue_1375". There are two problems here:

1. The StructuredGrid class was not handling degenerate grids where one or more dimensions were of length 1. This has been fixed in branch "issue_1375".

2. The second problem is more complex. The variable TLSB exists in a different spatial domain than the other variables in this data set. Specifically, the Z coordinate for TLSB ranges from [0.0, 4.0], whereas the other variables have Z extents in the range ~[30, 20,000]. The extents of the Box class are set using one of the other variables. When the wireframe or slice renderer are enabled and the TLSB variable is selected at the coarsest refinement level the Z dimension length is 1. Hence, the Z extents are [2.0, 2.0]. The min and max range for Z displayed in the GeometryWidget are both set to 2.0, but the Box still has the extents that it was initialized with with Z in the range [30, 20,000]. The slice and wireframe renderer both clip to the Box bounds, so nothing is shown. If the Z value were changed in the GeometryWidget this would force the GeometryWidget::setRange() signal to be triggered, and the Box would then have reasonable values. But not surprisingly Qt does not seem to generate a slider changed signal if the value is unchanged. The simple fix maybe to reset any box dimensions that are outside of the variable's dimensions during GeometryWidget::Update.

**Comment by clyne** [comment] 2020-01-06 18:19
Assigning to @sgpearse

**Comment by sgpearse** [comment] 2020-01-07 23:25
@clyne 

John, I've confirmed that that my recent tests were based off of the partial fix you committed in 
c4891c1.

I'm currently working on a branch named issue1375_part2.  This is resetting the Box extents in the VariablesWidget.  I'll see how this can be done in the GeometryWidget next.

I still believe there is another problem querying the Grid class for data values.  The Slice renderer and TFEditor are unable to acquire valid values for TSLB at its coarsest compression level.  This problem exists even when the Box is within the variable's domain.

**Comment by clyne** [comment] 2020-01-08 01:53
> @clyne
> 
> John, I've confirmed that that my recent tests were based off of the partial fix you committed in
> [c4891c1](https://github.com/NCAR/VAPOR/commit/c4891c11eb6c57f9892858668cd68a4ceb7ee05d).
> 
> I'm currently working on a branch named issue1375_part2. This is resetting the Box extents in the VariablesWidget. I'll see how this can be done in the GeometryWidget next.
> 

Is there a reason we have another branch to track?

> I still believe there is another problem querying the Grid class for data values. The Slice renderer and TFEditor are unable to acquire valid values for TSLB at its coarsest compression level. This problem exists even when the Box is within the variable's domain.

Well one thing at a time. Let's see if we can fix the GeometryWidget and get the WireFrame renderer working, then we can move on to the other renderers.

**Comment by sgpearse** [comment] 2020-01-08 03:33
> Is there a reason we have another branch to track?

Well, yes.  This is because we're finding that several problems cause this bug.  A new branch lets me isolate work on the current problem.  I can keep my changes separate from the previous fix (c4891c1).  

I think it's also convenient to make a new branch that can be discarded, rather than having to revert through commit hashes.  I also don't want to push my changes onto somebody else's branch without their feedback.  This is not my branch, and I prefer doing PR's on branches that are not my own.   If this is interfering with your workflow, please let me know.

> Well one thing at a time. Let's see if we can fix the GeometryWidget and get the WireFrame renderer working, then we can move on to the other renderers.

Sounds good.  I currently believe the problem is with the function Grid::GetValue( std::vector<float> coords ), returning missingValues when working with a Z-Dimension of size 1.  The link below illustrates the problem in the SliceRenderer.  The TFEditor is failing to sample data as well, but I'm not yet sure if it's making the same function call as the SliceRenderer.

https://github.com/NCAR/VAPOR/blob/b9df9243720298b039c84d04024b585692b67dae/lib/render/SliceRenderer.cpp#L323

**Comment by clyne** [comment] 2020-01-08 16:03
> > Is there a reason we have another branch to track?
> 
> Well, yes. This is because we're finding that several problems cause this bug. A new branch lets me isolate work on the current problem. I can keep my changes separate from the previous fix ([c4891c1](https://github.com/NCAR/VAPOR/commit/c4891c11eb6c57f9892858668cd68a4ceb7ee05d)).
> 
> I think it's also convenient to make a new branch that can be discarded, rather than having to revert through commit hashes. I also don't want to push my changes onto somebody else's branch without their feedback. This is not my branch, and I prefer doing PR's on branches that are not my own. If this is interfering with your workflow, please let me know.

It's not interfering with my workflow, but it seems like we've been down this road before and it's led to confusion with what changes have been made on what branch and how to get everything back together again. If you can keep everything straight it's not a problem for me.

> 
> > Well one thing at a time. Let's see if we can fix the GeometryWidget and get the WireFrame renderer working, then we can move on to the other renderers.
> 
> Sounds good. I currently believe the problem is with the function Grid::GetValue( std::vector coords ), returning missingValues when working with a Z-Dimension of size 1. The link below illustrates the problem in the SliceRenderer. The TFEditor is failing to sample data as well, but I'm not yet sure if it's making the same function call as the SliceRenderer.
> 
> https://github.com/NCAR/VAPOR/blob/b9df9243720298b039c84d04024b585692b67dae/lib/render/SliceRenderer.cpp#L323

I don't think that this is a bug. We're trying to sample an infinitesimally thin surface and we're missing it. What we may need is an option to slice along grid coordinates rather than user coordinates. We've had requests for this in the past.

**Closed** 2020-01-09 16:35 UTC
Labels: Bug, High
