### ISSUE TITLE
Flow list of seeds large number causes vapor to hang

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2979] opened 2022-01-24 21:13 UTC
1. Edit the default list of seeds file: `shared/example`
2. Add the following line to the end `.5,5000000000000000000000000000000000000,.5`
3. Enable a flow renderer and pick use `List of seeds` under seed distribution type

Vapor will hang.

**Comment by sgpearse** [comment] 2024-08-07 19:08
On M1, this causes VAPOR to crash when loading our zfp HDF5 file, and selecting a variable for advection (none are selected by default)

**Comment by shaomeng** [comment] 2024-08-08 18:45
Hey @StasJ , I cannot reproduce a hang using the dataset Scott suggested, on M1 MacBook. What platform did you test it on?
@sgpearse , I cannot reproduce a crash! We need to do a screen share probably...

**Comment by sgpearse** [comment] 2024-08-08 18:56
@shaomeng I think this works for stas.  I'm actually seeing it work too now.  Not sure why it crashed for me yesterday but I'll go ahead and close it.

**Closed by sgpearse** 2024-08-08 18:56 UTC
Labels: Bug, Medium, Fixed

**Comment by shaomeng** [comment] 2024-08-08 19:44
> @shaomeng I think this works for stas. I'm actually seeing it work too now. Not sure why it crashed for me yesterday but I'll go ahead and close it.

Hmm, thanks for testing it again. It sucks to give random crashes... I'll keep this issue in mind and come back to it as soon as I notice it again. Thanks a lot!
