### ISSUE TITLE
Slice Renderer sometimes creates phantom zones

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR#2149] opened 2020-01-23 17:05 UTC
Rendering in slice renderers creates zones that erase renderers in an inconsistent manner. In the attached files, only some of the slice renderers overlap and erase the other renders, while some only erase from one direction, and some erase from both directions.
All of these renderers show the same dataset, but all four are displaced on the Y coordinate. (These slice renderers display X and Z.)

Additionally, loading a 5th renderer causes paint to fail and VAPOR to crash. Paint fails randomly with slice renderers, regardless of the amount, dataset or settings.

![invis0025](https://user-images.githubusercontent.com/56135291/73006229-3186dc80-3e02-11ea-9ee6-27b9d87cb191.png)

![invis0070](https://user-images.githubusercontent.com/56135291/73006063-e240ac00-3e01-11ea-8be3-78de92ee4bcf.png)

![multipleslice2](https://user-images.githubusercontent.com/56135291/73006038-d8b74400-3e01-11ea-95f3-234838a3f1cb.gif)

**Impact**
- [ ] High - User productivity significantly degraded
- [x] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### To Reproduce
Load up multiple slice renderers and set them to XZ. Offset Y. Sometimes paint will fail and vapor will crash.

All of the datasets I've been using are the same as my previous bug reports.

### Desktop
 - OS and version: Red Hat Linux Enterprise 7
 - Version: VAPOR 3.2.0

**Comment by jvalan** [comment] 2020-01-23 18:09
![another slice](https://user-images.githubusercontent.com/56135291/73011046-72372380-3e0b-11ea-9411-173d597addbc.png)

**Comment by clyne** [comment] 2020-01-24 15:00
@stasj there are two issues being reported here. The first I believe is simply the lack of visibility ordering. Do you agree? The second is a crash. Can you please see if you can reproduce?

**Comment by StasJ** [comment] 2020-01-24 18:57
@clyne, you are correct that the first issue is depth sorting. @jvalan since vapor uses rasterization to generate visualizations, transparent objects need to be sorted in order to blend together correctly. We plan on making this automatic in cases such as these however it is a rather difficult task which we have not had time to tackle yet. Currently, you need to set the rendering order manually which is done by enabling the renderers in the correct order. Renderers are rendered in the order they are enabled, so you want to enable the renderers furthest away from you first and the renderers closest to you last. If you were to then rotate the camera to the opposite side, the rendering would be incorrect. Sorry about the inconvenience.

As to the crash, I cannot reproduce this. I created 10 transparent slice renderers without problems and I was using `vvdorian05l.2019082900.hwrfprs.storm.0p015.f066.nc` on my mac.

**Comment by StasJ** [comment] 2020-01-24 20:46
@clyne I re-tested this on Ubuntu and I still cannot reproduce the crash. It is possible that it as already been fixed in the current build.

**Comment by clyne** [comment] 2020-01-25 21:28
Let’s just close it then. Thanks, @stasj

> On Jan 24, 2020, at 1:46 PM, StasJ <notifications@github.com> wrote:
> 
> @clyne I re-tested this on Ubuntu and I still cannot reproduce the crash. It is possible that it as already been fixed in the current build.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Closed** 2020-01-26 01:33 UTC
Labels: Bug
