### ISSUE TITLE
Flow POP/KISTI crash

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2133] opened 2020-01-21 18:55 UTC
1. Import POP/KIST
2. Create/Enable Flow
3. Set X Var `HUS` and Y Var `HUW`
4. Change the Integration Steps to 50
5. Mess with the seed sliders

Vapor crashed. I tried the same thing a second time and it did not crash.

**Comment by shaomeng** [comment] 2020-01-27 19:34
Cannot reproduce on Linux.

Note: it seems for these specific variables, you'll need to set velocity multiplier to a very small value, 1e-7 for example, to view meaningful flowlines.

**Comment by clyne** [comment] 2020-01-27 21:50
@stasj please run through valgrind and see if you can turn anything up or generate a reproducable test case.

**Comment by StasJ** [comment] 2020-01-28 04:49
I repeated the instructions with valgrind and I did not see any invalid writes. There are many invalid reads and jumps on initialized values which could potentially be leading to unintended cases. I've attached the valgrind output here.

[valgrind2.txt](https://github.com/NCAR/VAPOR/files/4120684/valgrind2.txt)

**Comment by clyne** [comment] 2020-01-28 05:21
Wow. This is a lot of output. Most of it appears in the Python library and we probably don’t have any control over it. Stas, can this be filtered out?

@sgpearse one item I see that we could address is the conditional jump in VSlider.cpp:

Conditional jump or move depends on uninitialised value(s)
   at 0x6E6472: VSliderEdit::SetRange(double, double) (VSliderEdit.cpp:56)


> On Jan 27, 2020, at 9:49 PM, StasJ <notifications@github.com> wrote:
> 
> I repeated the instructions with valgrind and I did not see any invalid writes. There are many invalid reads and jumps on initialized values which could potentially be leading to unintended cases. I've attached the valgrind output here.
> 
> valgrind2.txt
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by shaomeng** [comment] 2020-01-28 06:23
I see one line is regard to FlowRenderer. I'll take a look at it tomorrow.

This summary is a little troublesome.
LEAK SUMMARY:
   definitely lost: 45,416 bytes in 282 blocks
   indirectly lost: 384,519 bytes in 2,512 blocks
     possibly lost: 58,216,988 bytes in 1,037,272 blocks
   still reachable: 13,988,202 bytes in 107,728 blocks
                      of which reachable via heuristic:
                        length64           : 20,312 bytes in 278 blocks
                        newarray           : 2,528 bytes in 78 blocks
                        multipleinheritance: 19,968 bytes in 13 block

**Comment by StasJ** [comment] 2020-01-28 17:05
@clyne last time I was working with valgrind I manually cleaned up the file since that was less work. I can make a suppression file that hides the python warnings for future use. I tried creating a regex but multiline regexes never seem to work as intended.. Here is the trimmed file.

[valgrind2.txt](https://github.com/NCAR/VAPOR/files/4123559/valgrind2.txt)

**Comment by clyne** [comment] 2020-01-28 19:09
Thanks for cleaning this up. It would be nice if we could automate in the future. Valgrind can be a powerful tool.

Anyway, Scott has already fixed the V widget problem. It’s clear now that there is also a problem in the Flow renderer for @shaomeng to look at as well.

**Comment by clyne** [comment] 2020-01-28 21:39
@stasj I think we should close this since we can't reproduce it. With luck the fixes that came out of the valgrind report will have addressed this. Thoughts?

**Comment by StasJ** [comment] 2020-01-28 21:43
@clyne I agree since valgrind did not show any fatal memory errors with this test case. After Sam looks at the problem shown in this valgrind log, I can rerun the Flow renderer through valgrind using one of the other datasets that have been problematic and see if that turns up anything new.

**Comment by clyne** [comment] 2020-01-28 21:45
@stasj great. FYI Sam and Scott have fixed the valgrind problems, and the PRs have been merged. I'd say go ahead and rerun your tests.

**Closed by clyne** 2020-01-28 21:45 UTC
Labels: Bug, High
