### ISSUE TITLE
Loading in multiple datasets at once creates a cube while paint fails

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR#1970] opened 2019-12-06 16:35 UTC
When importing in multiple files in order to create a time variable like this:
![Screenshot from 2019-12-06 16-11-38](https://user-images.githubusercontent.com/56135291/70338829-8ae07f80-1845-11ea-862c-19f712359a2d.png)
Not only does nothing render and give a paint fail error, the bounding box, which should normally be very rectangular, with a low z dimension becomes a cube. Previously this didn't happen before until I was given an installer of the latest test version.

![Screenshot from 2019-12-06 16-09-54](https://user-images.githubusercontent.com/56135291/70338989-d8f58300-1845-11ea-922c-0cfbf556e482.png)

**Helpful additional information**
(*Please click check boxes AFTER submitting ticket*)
- [ ] Did VAPOR crash?
- [x] Did you get wrong results?

**Impact**
- [ ] High - User productivity significantly degraded
- [ ] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### To Reproduce
Steps to reproduce the behavior. For example:
1. Go to File -> Import -. NET-cdf
2. select multiple files.
3. select okay

I've used the same datasets I sent days prior to replicate this bug.

### Desktop
 - OS and version: Redhat Enterprise Linux 7
 - Version: Vapor3-3.2.0.alpha-hdf5-1.10.1

**Comment by clyne** [comment] 2019-12-06 23:21
Duplicate of #1938

**Closed by clyne** 2019-12-06 23:21 UTC
Labels: Bug, Duplicate, Rejected
