### ISSUE TITLE
Crash on change fidelity with multiple visualizers

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1475] opened 2019-02-27 19:20 UTC
OS: OSX
Dataset: /little_glade/stasj/lee.nc

1. Add a visualizer
2. Add a renderer in both visualizers
3. Enable both renderers
4. Set the fidelity to max in the second renderer
5. Set the fidelity to max in the first renderer
6. Vapor will crash

I did this with two slice renderers however it appears to work with any combination. It sometimes takes two tries to crash.

**Comment by shaomeng** [comment] 2019-05-12 20:08
Cannot proceed far enough to reproduce this bug because of issue #1523 .

**Comment by shaomeng** [comment] 2019-05-13 21:44
Multiple visualizers and their controls seem to be **very** out of sync. See related report #1528

**Comment by shaomeng** [comment] 2019-05-22 00:55
Update on May21: though the controls of different renderers are still very out of sync, I cannot observe a crash anymore.

**Comment by shaomeng** [comment] 2019-05-29 19:08
It doesn't crash on May 29th, so I'm going to close it.

**Closed by shaomeng** 2019-05-29 19:08 UTC
Labels: Bug, High
