### ISSUE TITLE
Flow Renderer Dissappearing

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR#2151] opened 2020-01-23 21:57 UTC
### Describe the bug
When opening a session that contains a flow renderer active, the flow sometimes fails to render completely. Additionally, attempting to take a screen shot of a flow render crashes VAPOR, as do changing some flow renderer settings.

**Helpful additional information**
(*Please click check boxes AFTER submitting ticket*)
- [x] Did VAPOR crash?
- [ ] Did you get wrong results?

**Impact**
- [x] High - User productivity significantly degraded
- [ ] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### To Reproduce
Steps to reproduce the behavior. For example:
1. Open a 3d flow render. Set seed distribution to Random with Bias and set seed count to 300
2. Open an image render.
3. Save session.
4. Close VAPOR.
5. Open VAPOR, and load the previously saved session.
6. The Flow render will not appear.

### Desktop
 - OS and version: Redhat Linux Enterprise 7
 - Version: VAPOR 3.2.0

**Comment by jvalan** [comment] 2020-01-24 19:56
Additionally, it seems that once paint fails when a flow renderer is active, even if the paint that failed was an image renderer, the flow renderer will vanish and not reappear regardless of inputs.

**Comment by shaomeng** [comment] 2020-01-27 21:03
Cannot reproduce on one of our data sets. @jvalan , can you provide a data set that you used to reproduce this bug?

**Comment by jvalan** [comment] 2020-01-28 17:56
I've been using these .nc datasets. But I think that the fact that I am using Linux may be a factor in the errors that happen to me.

https://send.firefox.com/download/d1a969c0badd22fe/#lyLrhFF12-LliWLJEEgNWA

https://send.firefox.com/download/6638cd68805dbb21/#BYl2Irp_5F495tFKAlS_HQ

**Comment by shaomeng** [comment] 2020-01-28 18:03
> I've been using these .nc datasets. But I think that the fact that I am using Linux may be a factor in the errors that happen to me.
> 
> https://send.firefox.com/download/d1a969c0badd22fe/#lyLrhFF12-LliWLJEEgNWA
> 
> https://send.firefox.com/download/6638cd68805dbb21/#BYl2Irp_5F495tFKAlS_HQ

Thanks @jvalan . I'll test again using these specific data sets.

**Comment by shaomeng** [comment] 2020-01-28 21:13
Hi @jvalan , I cannot reproduce the reported bug using your data either. If it consistently appears on your system, can you provide a more specific step-by-step instruction to reproduce it?

**Comment by jvalan** [comment] 2020-01-30 18:22
I raised the integration steps to 850 and the vector field multiplier to 100. Seed count is at 320.

**Comment by jvalan** [comment] 2020-01-30 18:44
When selecting image capture, "Select destination" doesn't appear and VAPOR crashes shortly after.

**Comment by shaomeng** [comment] 2020-01-30 18:54
> I raised the integration steps to 850 and the vector field multiplier to 100. Seed count is at 320.

I'll try to reproduce it again with these specifications. Will likely be the next week though.

**Comment by shaomeng** [comment] 2020-01-30 18:55
> When selecting image capture, "Select destination" doesn't appear and VAPOR crashes shortly after.

This one sound like a separate issue regarding to image capture. Could you isolate the crash and provide a reproducible case in a new issue? Thanks!

**Comment by jvalan** [comment] 2020-01-30 19:02
Will do. Also, pan around with region to force VAPOR to make new seeded datapoints a bunch of times.

**Comment by sgpearse** [comment] 2020-01-31 19:20
I can reproduce the problem regarding the session file containing an enabled flow renderer, and no streamlines being drawn.

To reproduce on OSX:
1) Open Vapor, and import the two NetCDF-CF files in /little_glade/bugs/2151
2) Create a flow renderer.  Increase integration steps to 850, and vector field multiplier by 100.
3) Enable the flow renderer and save the session.
4) Close vapor, and re-open it with the previously created session file.  The renderer will be enabled, but nothing is drawn.

**Comment by clyne** [comment] 2020-01-31 19:24
The variables in this file are 2D. Let’s test it again after Sam gets PR #2141 merged. Thanks, Scott.

> On Jan 31, 2020, at 12:20 PM, sgpearse <notifications@github.com> wrote:
> 
> I can reproduce the problem regarding the session file containing an enabled flow renderer, and no streamlines being drawn.
> 
> To reproduce on OSX:
> 
> 	• Open Vapor, and import the two NetCDF-CF files in /little_glade/bugs/2151
> 	• Create a flow renderer. Increase integration steps to 850, and vector field multiplier by 100.
> 	• Enable the flow renderer and save the session.
> 	• Close vapor, and re-open it with the previously created session file. The renderer will be enabled, but nothing is drawn.
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Closed** 2020-01-31 20:39 UTC
Labels: Bug, High
