### ISSUE TITLE
Inconsistant behavior of renderers.

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#861] opened 2018-05-11 17:27 UTC
Behavior 1:
1. Open VAPOR, load DUKU, create a barb renderer.
2. Enable it, you see 16 barbs on the screen.
4. This is behavior 1. 

Behavior 2:
1. Open VAPOR, load Katrina.
2. Close Katrina.
3. Load DUKU, create a barb renderer.
2. Enable it, you see nothing on the screen. 
4. This is behavior 2. 

I believe there shouldn't be a discrepancy between behavior 1 and 2.

**Comment by sgpearse** [comment] 2018-05-11 21:41
Duplicate of #479

**Comment by shaomeng** [comment] 2018-12-20 19:21
Update on 12/20: This bug stays the same, and seems quite different issue #479 . Not sure why it was labeled `Duplicate`. @sgpearse

**Comment by sgpearse** [comment] 2023-10-31 18:10
No longer relevant.

**Closed by sgpearse** 2023-10-31 18:10 UTC
Labels: Duplicate, Bug
